Comment `index` set to Comment.all
Removed control flow bc it was causing error on Prod

NoMethodError (undefined method `author' for #<Comment:0x000055ccb79aad10>):
2020-04-02T19:49:57.636231+00:00 app[web.1]: [82771e77-0fa3-4bdd-be3d-de24b48231f6]
2020-04-02T19:49:57.636307+00:00 app[web.1]: [82771e77-0fa3-4bdd-be3d-de24b48231f6] app/controllers/comments_controller.rb:13:in `index'